const $=id=>document.getElementById(id),KEY="twStockBrokerV22";
let state=JSON.parse(localStorage.getItem(KEY)||'{"holdings":[],"watchlist":[]}'),tab="holdings",searched=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const fmt=n=>n==null||Number.isNaN(Number(n))?"—":Number(n).toLocaleString("zh-TW",{maximumFractionDigits:2});
const date=v=>v?new Date(v).toLocaleDateString("zh-TW",{timeZone:"Asia/Taipei"}):"日期不明";
const age=v=>{if(!v)return"日期不明";const d=Math.max(0,Math.floor((Date.now()-new Date(v))/86400000));return d?`${d} 天前`:"今天"};
function targetAge(v){if(!v)return{label:"日期不明",level:"unknown",expired:false};const d=Math.max(0,Math.floor((Date.now()-new Date(v))/86400000));if(d>180)return{label:"超過180天・已過期",level:"expired",expired:true};if(d>90)return{label:"91～180天・低參考",level:"low",expired:false};if(d>30)return{label:"31～90天・偏舊",level:"stale",expired:false};return{label:"30天內・正常",level:"fresh",expired:false}}
function status(t,e=false){$("statusText").textContent=t;$("statusText").className=e?"status error":"status"}
async function readJson(r,label){const text=await r.text();let j;try{j=JSON.parse(text)}catch{throw Error(`${label} API 未正常部署（HTTP ${r.status}）`)}if(!r.ok||!j.ok)throw Error(j.error||`${label}查詢失敗`);return j}
async function quote(code){const r=await fetch(`/api/quote?code=${code}`,{cache:"no-store"});return readJson(r,"股價")}
async function targets(code,name){const r=await fetch(`/api/targets?code=${code}&name=${encodeURIComponent(name||"")}`,{cache:"no-store"});const j=await readJson(r,"目標價");return j.brokers||[]}
async function load(code){const q=await quote(code);let brokers=[],targetError="";try{brokers=await targets(code,q.name)}catch(e){targetError=e.message}return{...q,brokers,targetError,lastRefresh:new Date().toISOString()}}
function normalizeHistoryItem(x){return{target:x?.target,date:x?.date||null,title:x?.title||"",sourceUrl:x?.sourceUrl||"",periodType:x?.periodType||"unknown",periodLabel:x?.periodLabel||"期間不明",revisionReason:x?.revisionReason||"unknown",revisionReasonLabel:x?.revisionReasonLabel||"原因不明"}}
function merge(oldRows=[],newRows=[]){const old=new Map(oldRows.map(x=>[x.broker,x])),fresh=new Map(newRows.map(x=>[x.broker,x])),out=[];for(const [b,x] of fresh){const o=old.get(b),changed=o&&(`${o.target}|${o.date}`!==`${x.target}|${x.date}`);const history=[...(x.targetHistory||[]),...(o?.targetHistory||[]),...(o?[o]:[])].map(normalizeHistoryItem).filter(x=>x.target).filter((x,i,a)=>a.findIndex(y=>y.target===x.target&&String(y.date||"").slice(0,10)===String(x.date||"").slice(0,10))===i).sort((a,b)=>new Date(b.date||0)-new Date(a.date||0)).slice(0,20);out.push({...x,periodType:x.periodType||"unknown",periodLabel:x.periodLabel||"期間不明",revisionReason:x.revisionReason||"unknown",revisionReasonLabel:x.revisionReasonLabel||"原因不明",targetHistory:history,previousTarget:history[1]?.target??null,previousDate:history[1]?.date??null,hasNewTarget:!!changed,isNewBroker:!o})}for(const [b,o] of old)if(!fresh.has(b))out.push({...o,periodType:o.periodType||"unknown",periodLabel:o.periodLabel||"期間不明",revisionReason:o.revisionReason||"unknown",revisionReasonLabel:o.revisionReasonLabel||"原因不明",hasNewTarget:false,isNewBroker:false,retained:true});return out.sort((a,b)=>a.brokerType!==b.brokerType?(a.brokerType==="外資"?-1:1):new Date(b.date||0)-new Date(a.date||0))}
function historyRows(h){return h.map((y,i)=>`<div class="history-item"><span>${i===0?"最新":i===1?"前次":i===2?"前前次":`第${i+1}筆`}</span><strong>${fmt(y.target)}</strong><span>${date(y.date)}</span>${y.sourceUrl?`<a href="${y.sourceUrl}" target="_blank" rel="noopener">來源</a>`:""}</div>`).join("")}
function historyHtml(x){const h=(x.targetHistory?.length?x.targetHistory:[normalizeHistoryItem(x)]);const recent=h.slice(0,3),older=h.slice(3);return`<details class="history-box"><summary>最近三次目標價</summary><div class="history-list">${historyRows(recent)}</div></details>${older.length?`<details class="history-box full-history"><summary>完整歷史（另有 ${older.length} 筆）</summary><div class="history-list">${historyRows(older)}</div></details>`:""}`}
function basis(x){if(x.previousTarget!=null&&x.target>x.previousTarget)return{value:x.previousTarget,label:"上調，採前次"};return{value:x.target,label:x.previousTarget==null?"僅一筆，採最新":x.target<x.previousTarget?"下調，採最新":"維持，採最新"}}
const PERIODS=[{key:"quarter",title:"季度目標價"},{key:"annual",title:"年度目標價"},{key:"12m",title:"12個月目標價"},{key:"unknown",title:"期間不明"}];
function brokerRow(x){const t=targetAge(x.date),b=basis(x);return`<div class="broker-row"><div class="broker-head"><div><strong>${x.broker}</strong> ${x.hasNewTarget?'<span class="badge new-badge">已更新</span>':''}${x.isNewBroker?'<span class="badge new-badge">新增券商</span>':''}${x.retained?'<span class="badge">保留舊資料</span>':''}<span class="badge age-${t.level}">${t.label}</span></div><strong>${fmt(x.target)}</strong></div><div class="small">${date(x.date)}（${age(x.date)}）${x.previousTarget?`｜前次 ${fmt(x.previousTarget)}`:""}</div><div class="info-line"><span class="badge">${x.periodLabel||"期間不明"}</span><span class="badge reason-${x.revisionReason||"unknown"}">${x.revisionReasonLabel||"原因不明"}</span></div><div class="small">倍率基準：${fmt(b.value)}（${b.label}）</div><div class="multiplier"><div>0.8<br><strong>${fmt(b.value*.8)}</strong></div><div>0.85<br><strong>${fmt(b.value*.85)}</strong></div><div>0.88<br><strong>${fmt(b.value*.88)}</strong></div></div>${historyHtml(x)}${x.sourceUrl?`<div class="small"><a href="${x.sourceUrl}" target="_blank" rel="noopener">查看最新來源</a></div>`:""}</div>`}
function periodGroups(list,type,expired=false){const eligible=(list||[]).filter(x=>x.brokerType===type&&targetAge(x.date).expired===expired);if(!eligible.length)return`<div class="small">${expired?"沒有過期資料":`目前沒有180天內可驗證的${type}目標價`}</div>`;return PERIODS.map(p=>{const a=eligible.filter(x=>(x.periodType||"unknown")===p.key);return a.length?`<div class="period-group"><h4>${p.title}</h4>${a.map(brokerRow).join("")}</div>`:""}).join("")}
function expiredSection(list){const expired=(list||[]).filter(x=>targetAge(x.date).expired);if(!expired.length)return"";return`<details class="expired-section"><summary>過期目標價（${expired.length} 家券商）</summary><div class="broker-section"><h3>外資券商</h3>${periodGroups(expired,"外資",true)}</div><div class="broker-section"><h3>本土券商</h3>${periodGroups(expired,"本土",true)}</div></details>`}
function targetSections(list){return`<div class="broker-section"><h3>外資券商</h3>${periodGroups(list,"外資",false)}</div><div class="broker-section"><h3>本土券商</h3>${periodGroups(list,"本土",false)}</div>${expiredSection(list)}`}
function card(x,i){const s=x.change>0?"+":"",c=x.change>0?"positive":x.change<0?"negative":"";return`<article class="stock-card"><div class="stock-head"><div><div class="stock-name">${x.name||"—"} <span class="code">${x.code}</span></div><div class="meta">${x.market||""}｜${x.quoteTime?new Date(x.quoteTime).toLocaleString("zh-TW"):"尚未更新"}</div></div><div><div class="price">${fmt(x.last)}</div><div class="${c}">${x.change==null?"—":`${s}${fmt(x.change)}（${s}${fmt(x.changePct)}%）`}</div></div></div>${targetSections(x.brokers)}<div class="actions"><button class="secondary refresh-one" data-i="${i}">刷新此檔</button><button class="secondary remove-one" data-i="${i}">刪除</button></div></article>`}
function render(){const a=state[tab];$("stockList").innerHTML=a.length?a.map(card).join(""):'<div class="empty">清單是空的</div>';document.querySelectorAll(".refresh-one").forEach(b=>b.onclick=()=>refreshOne(+b.dataset.i));document.querySelectorAll(".remove-one").forEach(b=>b.onclick=()=>{state[tab].splice(+b.dataset.i,1);save();render()})}
function show(x){searched=x;$("searchResult").classList.remove("hidden");$("searchResult").innerHTML=`<div class="stock-head"><div><div class="stock-name">${x.name} <span class="code">${x.code}</span></div><div class="meta">${x.market}｜Yahoo Finance</div></div><div class="price">${fmt(x.last)}</div></div>${targetSections(x.brokers)}<div class="actions"><button id="addH">加入持股</button><button id="addW" class="secondary">加入觀察</button></div>`;$("addH").onclick=()=>add("holdings");$("addW").onclick=()=>add("watchlist")}
function add(type){if(state[type].some(x=>x.code===searched.code))return status("清單中已存在");state[type].push(searched);tab=type;save();tabs();render();status("已加入清單")}
async function search(){const code=$("stockCode").value.trim();if(!/^\d{4,6}$/.test(code))return status("請輸入正確股票代碼",true);$("searchButton").disabled=true;status("正在更新股價與各券商目標價…");try{const x=await load(code);show(x);status(`更新成功：${x.name}`)}catch(e){status(e.message,true)}finally{$("searchButton").disabled=false}}
async function refreshOne(i){const old=state[tab][i];status(`正在刷新 ${old.name||old.code}…`);try{const x=await load(old.code);x.brokers=merge(old.brokers,x.brokers);state[tab][i]=x;save();render();status(`${x.name} 已刷新`)}catch(e){status(e.message,true)}}
async function refreshAll(){const all=[...state.holdings.map((x,i)=>({t:"holdings",i,x})),...state.watchlist.map((x,i)=>({t:"watchlist",i,x}))];if(!all.length)return status("清單是空的");$("refreshAllButton").disabled=true;for(let n=0;n<all.length;n++){const a=all[n];status(`刷新中 ${n+1}/${all.length}：${a.x.name||a.x.code}`);try{const x=await load(a.x.code);x.brokers=merge(a.x.brokers,x.brokers);state[a.t][a.i]=x}catch(e){state[a.t][a.i].refreshError=e.message}save();render()}$("refreshAllButton").disabled=false;status("持股與觀察清單已全部刷新")}
function tabs(){document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab))}
$("searchButton").onclick=search;$("stockCode").onkeydown=e=>{if(e.key==="Enter")search()};$("refreshAllButton").onclick=refreshAll;document.querySelectorAll("[data-code]").forEach(b=>b.onclick=()=>{$("stockCode").value=b.dataset.code;search()});document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;tabs();render()});render();
