const $=id=>document.getElementById(id),KEY="twStockBrokerV23";
const previous=JSON.parse(localStorage.getItem("twStockBrokerV22")||"null");
let state=JSON.parse(localStorage.getItem(KEY)||JSON.stringify(previous||{holdings:[],watchlist:[],sortModes:{holdings:"custom",watchlist:"custom"}}));
state.holdings??=[];state.watchlist??=[];state.sortModes??={holdings:"custom",watchlist:"custom"};state.searchHistory??=[];
let searched=null,currentPage="search";
const expanded={holdings:new Set(),watchlist:new Set()};
const busy=new Set();
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const fmt=n=>n==null||Number.isNaN(Number(n))?"—":Number(n).toLocaleString("zh-TW",{maximumFractionDigits:2});
const date=v=>v?new Date(v).toLocaleDateString("zh-TW",{timeZone:"Asia/Taipei"}):"日期不明";
const age=v=>{if(!v)return"日期不明";const d=Math.max(0,Math.floor((Date.now()-new Date(v))/86400000));return d?`${d}天前`:"今天"};
const isRecent=v=>v&&Math.max(0,Math.floor((Date.now()-new Date(v))/86400000))<=180;
function status(t,e=false){$("statusText").textContent=t;$("statusText").className=e?"status error":"status"}
function escapeHtml(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function renderSearchHistory(){const el=$("searchHistory");if(!el)return;el.innerHTML=state.searchHistory.length?state.searchHistory.map((x,i)=>`<div class="history-chip"><button class="history-query" data-history-i="${i}">${escapeHtml(x.name||x.query||x.code)}</button><button class="history-delete" data-history-delete="${i}" aria-label="刪除 ${escapeHtml(x.name||x.query||x.code)}">×</button></div>`).join(""):'<span class="search-history-empty">尚無搜尋紀錄</span>';document.querySelectorAll(".history-query").forEach(b=>b.onclick=()=>{const x=state.searchHistory[+b.dataset.historyI];$("stockCode").value=x.code||x.query||x.name;search()});document.querySelectorAll(".history-delete").forEach(b=>b.onclick=e=>{e.stopPropagation();state.searchHistory.splice(+b.dataset.historyDelete,1);save();renderSearchHistory()})}
function addSearchHistory(x,query){const item={code:x.code,name:x.name,query:String(query||x.code)};state.searchHistory=[item,...state.searchHistory.filter(y=>y.code!==item.code)].slice(0,12);save();renderSearchHistory()}
async function readJson(r,label){const text=await r.text();let j;try{j=JSON.parse(text)}catch{throw Error(`${label} API 未正常部署（HTTP ${r.status}）`)}if(!r.ok||!j.ok)throw Error(j.error||`${label}查詢失敗`);return j}
async function quote(query){return readJson(await fetch(`/api/quote?q=${encodeURIComponent(query)}`,{cache:"no-store"}),"股價")}
async function targets(code,name){const j=await readJson(await fetch(`/api/targets?code=${code}&name=${encodeURIComponent(name||"")}`,{cache:"no-store"}),"目標價");return j.brokers||[]}
async function load(query){const q=await quote(query);let brokers=[],targetError="";try{brokers=await targets(q.code,q.name)}catch(e){targetError=e.message}return{...q,brokers,targetError,lastRefresh:new Date().toISOString()}}
function normalizeHistoryItem(x){return{target:x?.target,date:x?.date||null,title:x?.title||"",sourceUrl:x?.sourceUrl||"",periodType:x?.periodType||"unknown",periodLabel:x?.periodLabel||"",revisionReason:x?.revisionReason||"unknown",revisionReasonLabel:x?.revisionReasonLabel||""}}
function rowKey(x){return x.brokerKey||x.broker||"未知券商"}
function merge(oldRows=[],newRows=[]){const old=new Map(oldRows.map(x=>[rowKey(x),x])),fresh=new Map(newRows.map(x=>[rowKey(x),x])),out=[];for(const[k,x]of fresh){const o=old.get(k),changed=o&&(`${o.target}|${o.date}`!==`${x.target}|${x.date}`);const history=[...(x.targetHistory||[]),...(o?.targetHistory||[]),...(o?[o]:[])].map(normalizeHistoryItem).filter(x=>x.target).filter((x,i,a)=>a.findIndex(y=>y.target===x.target&&String(y.date||"").slice(0,10)===String(x.date||"").slice(0,10))===i).sort((a,b)=>new Date(b.date||0)-new Date(a.date||0)).slice(0,5);out.push({...x,broker:x.broker||"未知券商",brokerKey:k,targetHistory:history,previousTarget:history[1]?.target??null,previousDate:history[1]?.date??null,hasNewTarget:!!changed,isNewBroker:!o})}for(const[k,o]of old)if(!fresh.has(k))out.push({...o,broker:o.broker||"未知券商",brokerKey:k,targetHistory:(o.targetHistory||[o]).map(normalizeHistoryItem).slice(0,5),hasNewTarget:false,isNewBroker:false,retained:true});return out.sort((a,b)=>a.brokerType!==b.brokerType?(a.brokerType==="外資"?-1:1):new Date(b.date||0)-new Date(a.date||0))}
function basis(x){if(x.previousTarget!=null&&x.target>x.previousTarget)return{value:Number(x.previousTarget),label:"上調，採前次"};return{value:Number(x.target),label:x.previousTarget==null?"僅一筆，採最新":x.target<x.previousTarget?"下調，採最新":"維持，採最新"}}
function stageForBroker(row,last){const b=basis(row).value;if(!Number.isFinite(b)||!Number.isFinite(Number(last)))return null;const p=Number(last),levels=[.8,.85,.88].map(rate=>({rate,price:b*rate}));if(p>=levels[2].price)return{rank:0,distance:0,label:"已達88%",broker:row.broker||"未知券商",price:levels[2].price};const next=levels.find(x=>p<x.price);const distance=(next.price-p)/p*100;return{rank:1,distance,label:`距${Math.round(next.rate*100)}%還差 ${distance.toFixed(1)}%`,broker:row.broker||"未知券商",price:next.price}}
function bestStage(stock){const rows=(stock.brokers||[]).filter(x=>isRecent(x.date)&&Number(x.target)>0),stages=rows.map(x=>stageForBroker(x,stock.last)).filter(Boolean);if(!stages.length)return null;return stages.sort((a,b)=>a.rank-b.rank||a.distance-b.distance)[0]}
function sortedItems(type){const a=state[type].map((x,index)=>({x,index}));if(state.sortModes[type]!=="targetDistance")return a;return a.sort((u,v)=>{const a=bestStage(u.x),b=bestStage(v.x);if(!a&&!b)return u.index-v.index;if(!a)return 1;if(!b)return-1;return a.rank-b.rank||a.distance-b.distance||u.index-v.index})}
function historyRows(h,start=0){return h.map((y,i)=>`<div class="history-item"><span>${start+i===0?"最新":start+i===1?"前次":`第${start+i+1}筆`}</span><strong>${fmt(y.target)}</strong><span>${date(y.date)}</span>${y.sourceUrl?`<a href="${y.sourceUrl}" target="_blank" rel="noopener">來源</a>`:""}</div>`).join("")}
function historyHtml(x){const h=(x.targetHistory?.length?x.targetHistory:[normalizeHistoryItem(x)]).slice(0,5),shown=h.slice(0,2),older=h.slice(2);return`<div class="history-list">${historyRows(shown)}</div>${older.length?`<details class="target-history"><summary>較早目標價（${older.length}）</summary>${historyRows(older,2)}</details>`:""}`}
const PERIODS=[{key:"quarter",title:"季度目標價"},{key:"annual",title:"年度目標價"},{key:"12m",title:"12個月目標價"},{key:"unknown",title:"其他目標價"}];
function brokerRow(x,last){const b=basis(x),info=[],stage=stageForBroker(x,last);if(x.periodType&&x.periodType!=="unknown"&&x.periodLabel)info.push(`<span class="badge">${x.periodLabel}</span>`);if(x.revisionReason&&x.revisionReason!=="unknown"&&x.revisionReasonLabel)info.push(`<span class="badge">${x.revisionReasonLabel}</span>`);return`<div class="broker-row"><div class="broker-head"><div><strong>${x.broker||"未知券商"}</strong> ${x.hasNewTarget?'<span class="badge new-badge">已更新</span>':''}${x.isNewBroker?'<span class="badge new-badge">新增</span>':''}</div><strong>${fmt(x.target)}</strong></div><div class="small">${date(x.date)}（${age(x.date)}）</div>${info.length?`<div class="info-line">${info.join("")}</div>`:""}${stage?`<div class="stage-line">${stage.label}</div>`:""}<div class="small">倍率基準：${fmt(b.value)}（${b.label}）</div><div class="multiplier"><div>80%<br><strong>${fmt(b.value*.8)}</strong></div><div>85%<br><strong>${fmt(b.value*.85)}</strong></div><div>88%<br><strong>${fmt(b.value*.88)}</strong></div></div>${historyHtml(x)}${x.sourceUrl?`<div class="small"><a href="${x.sourceUrl}" target="_blank" rel="noopener">查看最新來源</a></div>`:""}</div>`}
function periodGroups(list,type,last){const eligible=(list||[]).filter(x=>x.brokerType===type&&isRecent(x.date));if(!eligible.length)return'<div class="small">近期無目標價</div>';return PERIODS.map(p=>{const a=eligible.filter(x=>(x.periodType||"unknown")===p.key);return a.length?`<div class="period-group"><h4>${p.title}</h4>${a.map(x=>brokerRow(x,last)).join("")}</div>`:""}).join("")}
function targetSections(list,last,refreshButton=""){return`<div class="target-title"><h3>目標價</h3>${refreshButton}</div><div class="broker-section"><h3>外資券商</h3>${periodGroups(list,"外資",last)}</div><div class="broker-section"><h3>本土券商</h3>${periodGroups(list,"本土",last)}</div><div class="broker-section"><h3>未知券商</h3>${periodGroups(list,"未知",last)}</div>`}
const icon=(kind,type,index,label)=>`<button class="icon-button ${kind}" data-type="${type}" data-i="${index}" aria-label="${label}" title="${label}"><span aria-hidden="true">${kind==="remove-one"?"×":"↻"}</span></button>`;
function card(x,index,type){const s=x.change>0?"+":"",c=x.change>0?"positive":x.change<0?"negative":"",key=`${type}:${x.code}`,open=expanded[type].has(key),stage=bestStage(x),custom=state.sortModes[type]==="custom";return`<article class="stock-card ${open?"expanded":""}" data-key="${key}" data-index="${index}" data-type="${type}" ${custom?'data-draggable="true"':''}>${icon("remove-one",type,index,"刪除股票")}<button class="stock-summary" data-toggle="${key}" aria-expanded="${open}"><div class="stock-summary-main"><div class="stock-name">${x.name||"—"} <span class="code">${x.code}</span><span class="chevron">⌄</span></div><div class="meta">${x.market||""}｜${x.quoteTime?new Date(x.quoteTime).toLocaleString("zh-TW"):"尚未更新"}</div>${type==="holdings"&&stage?`<div class="summary-stage">${stage.broker}：${stage.label}</div>`:""}</div><div class="stock-price"><div class="price-line"><div class="price">${fmt(x.last)}</div>${icon("refresh-quote",type,index,"刷新即時股價")}</div><div class="${c}">${x.change==null?"—":`${s}${fmt(x.change)}（${s}${fmt(x.changePct)}%）`}</div></div></button><div class="stock-detail">${targetSections(x.brokers,x.last,icon("refresh-targets",type,index,"刷新目標價"))}</div></article>`}
function renderList(type){const el=$(type+"List"),a=sortedItems(type);el.innerHTML=a.length?a.map(({x,index})=>card(x,index,type)).join(""):'<div class="empty">清單是空的</div>'}
function renderAll(){renderList("holdings");renderList("watchlist");bindLists();document.querySelectorAll("[data-sort-list]").forEach(s=>s.value=state.sortModes[s.dataset.sortList]||"custom")}
function replaceStock(type,i,patch){state[type][i]={...state[type][i],...patch};save();renderAll()}
async function refreshQuoteOne(type,i,button){const old=state[type][i],key=`q:${type}:${i}`;if(busy.has(key))return;busy.add(key);button?.classList.add("spinning");button&&(button.disabled=true);try{const q=await quote(old.code);replaceStock(type,i,{...q,brokers:old.brokers,lastRefresh:new Date().toISOString()});status(`${old.name||old.code} 股價已刷新`)}catch(e){status(e.message,true)}finally{busy.delete(key)}}
async function refreshTargetsOne(type,i,button){const old=state[type][i],key=`t:${type}:${i}`;if(busy.has(key))return;busy.add(key);button?.classList.add("spinning");button&&(button.disabled=true);try{const rows=await targets(old.code,old.name);replaceStock(type,i,{brokers:merge(old.brokers,rows),targetError:"",lastTargetRefresh:new Date().toISOString()});status(`${old.name||old.code} 目標價已刷新`)}catch(e){status(e.message,true)}finally{busy.delete(key)}}
function bindLists(){document.querySelectorAll("[data-toggle]").forEach(b=>b.onclick=()=>{const[type]=b.dataset.toggle.split(":");expanded[type].has(b.dataset.toggle)?expanded[type].delete(b.dataset.toggle):expanded[type].add(b.dataset.toggle);renderAll()});document.querySelectorAll(".refresh-quote").forEach(b=>b.onclick=e=>{e.stopPropagation();refreshQuoteOne(b.dataset.type,+b.dataset.i,b)});document.querySelectorAll(".refresh-targets").forEach(b=>b.onclick=e=>{e.stopPropagation();refreshTargetsOne(b.dataset.type,+b.dataset.i,b)});document.querySelectorAll(".remove-one").forEach(b=>b.onclick=e=>{e.stopPropagation();const type=b.dataset.type,i=+b.dataset.i,x=state[type][i];if(confirm(`確定刪除 ${x.name||x.code}？`)){state[type].splice(i,1);save();renderAll()}});bindDrag()}
function show(x){searched=x;$("searchResult").classList.remove("hidden");$("searchResult").innerHTML=`<div class="search-result-head"><div><div class="stock-name">${x.name} <span class="code">${x.code}</span></div><div class="meta">${x.market}｜Yahoo Finance</div></div><div class="stock-price"><div class="price-line"><div class="price">${fmt(x.last)}</div><button id="searchQuoteRefresh" class="icon-button" aria-label="刷新即時股價"><span>↻</span></button></div></div></div>${targetSections(x.brokers,x.last,'<button id="searchTargetsRefresh" class="icon-button" aria-label="刷新目標價"><span>↻</span></button>')}<div class="actions"><button id="addH">加入持股</button><button id="addW" class="secondary">加入觀察</button></div>`;$("addH").onclick=()=>add("holdings");$("addW").onclick=()=>add("watchlist");$("searchQuoteRefresh").onclick=async e=>{const b=e.currentTarget;b.classList.add("spinning");try{const q=await quote(searched.code);searched={...searched,...q};show(searched);status(`${searched.name} 股價已刷新`)}catch(err){status(err.message,true)}};$("searchTargetsRefresh").onclick=async e=>{const b=e.currentTarget;b.classList.add("spinning");try{searched.brokers=merge(searched.brokers,await targets(searched.code,searched.name));show(searched);status(`${searched.name} 目標價已刷新`)}catch(err){status(err.message,true)}}}
function add(type){if(state[type].some(x=>x.code===searched.code))return status("清單中已存在");state[type].push({...searched});save();renderAll();goPage(type);status("已加入清單")}
async function search(){const q=$("stockCode").value.trim();if(!q)return status("請輸入股票名稱或代碼",true);$("searchButton").disabled=true;status("正在更新股價與各券商目標價…");try{const x=await load(q);show(x);addSearchHistory(x,q);status(`更新成功：${x.name}`)}catch(e){status(e.message,true)}finally{$("searchButton").disabled=false}}
function bindDrag(){document.querySelectorAll('[data-draggable="true"]').forEach(card=>{let timer,startY,dragging=false;const start=e=>{if(e.target.closest("button,a,details,summary"))return;startY=e.clientY??e.touches?.[0]?.clientY;timer=setTimeout(()=>{dragging=true;card.classList.add("dragging");navigator.vibrate?.(25)},420)};const move=e=>{if(!dragging)return;e.preventDefault();const y=e.clientY??e.touches?.[0]?.clientY;const type=card.dataset.type,container=$(type+"List"),others=[...container.querySelectorAll('[data-draggable="true"]:not(.dragging)')],after=others.find(el=>y<el.getBoundingClientRect().top+el.offsetHeight/2);after?container.insertBefore(card,after):container.appendChild(card)};const end=()=>{clearTimeout(timer);if(!dragging)return;dragging=false;card.classList.remove("dragging");const type=card.dataset.type,codes=[...$(type+"List").querySelectorAll(".stock-card")].map(el=>el.dataset.key.split(":").slice(1).join(":"));state[type].sort((a,b)=>codes.indexOf(a.code)-codes.indexOf(b.code));save();renderAll()};card.addEventListener("pointerdown",start);card.addEventListener("pointermove",move);card.addEventListener("pointerup",end);card.addEventListener("pointercancel",end)})}
const pages=["search","holdings","watchlist"];
function updatePageTabs(page){currentPage=page;document.querySelectorAll(".page-tab").forEach(b=>b.classList.toggle("active",b.dataset.page===page))}
function goPage(page){const i=pages.indexOf(page);if(i<0)return;$("pageTrack").scrollTo({left:$("pageTrack").clientWidth*i,behavior:"smooth"});updatePageTabs(page)}
let scrollTimer;$("pageTrack").addEventListener("scroll",()=>{clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>{const i=Math.round($("pageTrack").scrollLeft/$("pageTrack").clientWidth);updatePageTabs(pages[Math.max(0,Math.min(2,i))])},80)});
document.querySelectorAll(".page-tab").forEach(b=>b.onclick=()=>goPage(b.dataset.page));
$("searchButton").onclick=search;$("stockCode").onkeydown=e=>{if(e.key==="Enter")search()};document.querySelectorAll("[data-sort-list]").forEach(s=>s.onchange=()=>{state.sortModes[s.dataset.sortList]=s.value;save();renderAll()});
renderAll();renderSearchHistory();
