const assert=require('node:assert/strict');
const fs=require('node:fs');
const tax=require('../lib/market-topic-taxonomy');
const freeze=require('../lib/final-taxonomy-freeze');
const {STORAGE_POLICY}=require('../lib/storage-policy');
const xy=fs.readFileSync('lib/fundflow-xy.js','utf8');
const app=fs.readFileSync('app.js','utf8');
const technical=fs.readFileSync('api/technical.js','utf8');
const status=fs.readFileSync('api/sync-status.js','utf8');
const html=fs.readFileSync('index.html','utf8');
assert.equal(tax.listMarketDefinitions({finalOnly:true}).length,191);
assert.equal(freeze.STATS.taxonomyCount,191);
assert(xy.includes('const definitions=registry;'),'browser definition universe must always be frozen 191 taxonomy');
assert(xy.includes('company_map_version'),'snapshot table must persist Company_Map version');
assert(xy.includes('AND company_map_version=$7'),'prepared snapshot read must require Company_Map version');
assert(xy.includes('companyMapFreezeVersion:COMPANY_MAP_VERSION'),'overview/browser payloads must carry the same Company_Map version as the snapshot row');
assert(xy.includes("snapshot-7.0.3-focuspack-path31-taxonomy25-browser191"),'snapshot schema must invalidate old 187-category payloads');
assert.equal(STORAGE_POLICY.referenceBudgetMb,1024);
assert.equal(STORAGE_POLICY.softTargetMb,800);
assert.equal(STORAGE_POLICY.compact.topicOperational,250);
assert.equal(STORAGE_POLICY.compact.topicResearch,500);
assert.equal(STORAGE_POLICY.compact.wResearch,500);
assert(status.includes('readResearchCompactHistoryStatus'));
assert(status.includes('researchReady500=liveReady&&researchDays>=targets.research'));
assert(xy.includes("storageLayer:'research-daily-numeric'"));
assert(html.includes('500D Research'));
assert(app.includes('technical-v26614:'),'technical cache namespace must invalidate stale .13 entries');
assert(app.includes('cacheCoversLatest'),'technical cache must compare payload date with latest quote trade date');
assert(technical.includes("Promise.allSettled(['query1.finance.yahoo.com','query2.finance.yahoo.com']"),'technical Yahoo loader must compare both Yahoo chart hosts');
assert(technical.includes("String(req.query?.refresh||'')==='1'?'no-store'"),'forced technical/history refresh must bypass CDN cache');
console.log('PASS v2.6.6.14 — 191-category browser + version-locked snapshots + 500D compact research + fresh Yahoo technical history');
