const HEADERS={"User-Agent":"Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 Chrome/126 Mobile Safari/537.36","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","Accept-Language":"zh-TW,zh;q=0.9,en;q=0.7"};
const BROKERS=[
["摩根士丹利","外資"],["大摩","外資"],["摩根大通","外資"],["小摩","外資"],["高盛證券","外資"],["高盛","外資"],["花旗","外資"],["美銀","外資"],["瑞銀","外資"],["瑞信","外資"],["野村","外資"],["麥格理","外資"],["匯豐","外資"],["滙豐","外資"],["里昂","外資"],["巴克萊","外資"],["德意志","外資"],["亞系外資","外資"],["美系外資","外資"],["歐系外資","外資"],["日系外資","外資"],
["元大","本土"],["群益","本土"],["凱基","本土"],["富邦","本土"],["國泰","本土"],["永豐","本土"],["統一","本土"],["兆豐","本土"],["第一金","本土"],["華南永昌","本土"],["玉山","本土"],["台新","本土"],["康和","本土"],["宏遠","本土"],["國票","本土"],["新光","本土"],["中國信託綜合證券","本土"],["中國信託證券","本土"],["中信投顧","本土"],["中信","本土"]
];
const CANONICAL={"高盛證券":"高盛","大摩":"摩根士丹利","小摩":"摩根大通","滙豐":"匯豐","中國信託綜合證券":"中信","中國信託證券":"中信","中信投顧":"中信"};
const clean=s=>String(s||"").replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/&nbsp;|&#160;/g," ").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
function clause(text,index){const stop=/[。；;！!?？\n]/;let s=index,e=index;while(s>0&&!stop.test(text[s-1]))s--;while(e<text.length&&!stop.test(text[e]))e++;return text.slice(s,e)}
function brokerMatches(text){const out=[];for(const [name,type] of BROKERS){let p=0;while((p=text.indexOf(name,p))!==-1){out.push({broker:CANONICAL[name]||name,brokerType:type,index:p});p+=name.length}}return out.sort((a,b)=>a.index-b.index)}
function targets(text){const out=[],patterns=[/目標價(?:由|從)?\s*(?:最高|上看|調升至|調高至|下修至|維持在|維持|喊到|看至|達到|為)?\s*(?:新台幣|台幣)?\s*([\d,]+(?:\.\d+)?)\s*元?/gi,/(?:上看|調升至|調高至|下修至|喊到|看至)\s*(?:新台幣|台幣)?\s*([\d,]+(?:\.\d+)?)\s*元/gi];for(const p of patterns){let m;while((m=p.exec(text))){const n=Number(m[1].replace(/,/g,""));if(!Number.isFinite(n)||n<10||n>100000)continue;const c=clause(text,m.index);if(/(?:EPS|每股盈餘|每股稅後盈餘)/i.test(c)&&!/目標價/i.test(c))continue;out.push({target:n,index:m.index})}}return out.filter((x,i,a)=>a.findIndex(y=>y.target===x.target&&Math.abs(y.index-x.index)<8)===i)}
function segment(text,code,name){const marks=[];if(name){let p=0;while((p=text.indexOf(name,p))!==-1){marks.push({index:p,requested:true});p+=name.length}}let cp=0;while((cp=text.indexOf(code,cp))!==-1){marks.push({index:cp,requested:true});cp+=code.length}const other=/([\u4e00-\u9fffA-Za-z][\u4e00-\u9fffA-Za-z0-9\-]{1,24})\s*[（(]\s*(\d{4,6})(?:\.TW|\.TWO)?\s*[）)]/g;let m;while((m=other.exec(text)))marks.push({index:m.index,requested:m[2]===code||(name&&m[1].includes(name))});marks.sort((a,b)=>a.index-b.index);const first=marks.find(x=>x.requested);if(!first)return text;const next=marks.find(x=>x.index>first.index&&!x.requested);return text.slice(first.index,next?.index||text.length)}
async function fetchPage(url){const c=new AbortController(),timer=setTimeout(()=>c.abort(),6000);try{const r=await fetch(url,{headers:HEADERS,redirect:"follow",signal:c.signal});if(!r.ok)throw Error(`來源網站回應 ${r.status}`);const html=await r.text();return clean(html)}finally{clearTimeout(timer)}}
module.exports=async function handler(req,res){res.setHeader("Cache-Control","no-store");if(req.method!=="POST")return res.status(405).json({ok:false,error:"僅支援 POST"});try{const body=typeof req.body==="string"?JSON.parse(req.body):req.body||{},url=String(body.url||"").trim(),code=String(body.code||"").replace(/\.(?:TW|TWO)$/i,"").trim(),name=String(body.name||"").trim(),mode=String(body.mode||"");if(!/^https?:\/\//i.test(url))return res.status(400).json({ok:false,error:"來源網址格式錯誤"});if(!/^\d{4,6}$/.test(code))return res.status(400).json({ok:false,error:"股票代碼格式錯誤"});const full=await fetchPage(url),text=segment(full,code,name),bs=brokerMatches(text),ts=targets(text);if(mode==="broker"){const b=bs[0];return res.status(200).json({ok:true,broker:b?.broker||null,brokerType:b?.brokerType||null,candidates:bs.map(x=>x.broker).filter((x,i,a)=>a.indexOf(x)===i)})}if(mode==="target"){const current=Number(body.currentTarget),different=ts.map(x=>x.target).filter(x=>x!==current);return res.status(200).json({ok:true,target:different.length===1?different[0]:null,candidates:ts.map(x=>x.target).filter((x,i,a)=>a.indexOf(x)===i)})}return res.status(400).json({ok:false,error:"修正類型錯誤"})}catch(e){return res.status(502).json({ok:false,error:"來源重新解析失敗",detail:e.message})}}

