const UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36';
function clean(v=''){return String(v??'').replace(/<[^>]*>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/\u3000/g,' ').replace(/\s+/g,' ').trim()}
function pick(obj,keys){for(const k of keys){if(obj&&obj[k]!==undefined&&obj[k]!==null&&clean(obj[k])!=='')return clean(obj[k])}return ''}
async function fetchText(url,timeoutMs=7000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(url,{headers:{'user-agent':UA,'accept':'application/json,text/html,text/plain,*/*','accept-language':'zh-TW,zh;q=0.9'},redirect:'follow',signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}
async function fetchJson(url,timeoutMs=7000){return JSON.parse(await fetchText(url,timeoutMs))}
function normalizeRows(rows,market){if(!Array.isArray(rows))return [];const out=[];for(const x of rows){const code=pick(x,['Code','code','SecuritiesCompanyCode','SecuritiesCode','公司代號','股票代號','證券代號','股票代碼']);const name=pick(x,['Name','name','CompanyName','SecuritiesCompanyName','公司簡稱','股票名稱','證券名稱','公司名稱']);if(!/^\d{4,6}$/.test(code)||!name)continue;out.push({code,name,market})}return out}
function parseTpexHtml(html){const out=[];for(const tr of String(html||'').match(/<tr\b[^>]*>[\s\S]*?<\/tr>/gi)||[]){const cells=[...tr.matchAll(/<t[dh]\b[^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(m=>clean(m[1]));if(cells.length<2)continue;const code=cells.find(x=>/^\d{4,6}$/.test(x));if(!code)continue;const i=cells.indexOf(code),name=clean(cells[i+1]||'');if(name&&!/^[-+\d.,]+$/.test(name))out.push({code,name,market:'上櫃'})}return out}
async function listedRows(){for(const u of ['https://openapi.twse.com.tw/v1/exchangeReport/STOCK_DAY_ALL','https://openapi.twse.com.tw/v1/opendata/t187ap03_L']){try{const r=normalizeRows(await fetchJson(u),'上市');if(r.length)return r}catch{}}return []}
async function otcRows(){for(const u of ['https://www.tpex.org.tw/openapi/v1/mopsfin_t187ap03_O','https://www.tpex.org.tw/openapi/v1/tpex_mainboard_daily_close_quotes','https://www.tpex.org.tw/openapi/v1/tpex_mainboard_quotes']){try{const r=normalizeRows(await fetchJson(u),'上櫃');if(r.length)return r}catch{}}for(const u of ['https://www.tpex.org.tw/web/stock/aftertrading/daily_close_quotes/stk_quote_result.php?l=zh-tw&o=htm','https://www.tpex.org.tw/web/stock/aftertrading/daily_close_quotes/stk_quote_result.php?d=&l=zh-tw&o=htm']){try{const r=parseTpexHtml(await fetchText(u));if(r.length)return r}catch{}}return []}
async function misByCode(code){if(!/^\d{4,6}$/.test(code))return null;try{const ex=`tse_${code}.tw|otc_${code}.tw`,j=await fetchJson(`https://mis.twse.com.tw/stock/api/getStockInfo.jsp?ex_ch=${encodeURIComponent(ex)}&json=1&delay=0`);const rows=Array.isArray(j?.msgArray)?j.msgArray:[];const x=rows.find(v=>String(v?.c||'')===code&&clean(v?.n));if(!x)return null;return {code,name:clean(x.n),market:x.ex==='otc'?'上櫃':'上市'}}catch{return null}}
function rank(row,q){const code=row.code,name=clean(row.name),needle=clean(q),flat=s=>s.replace(/[-－]/g,'');if(code===needle)return 1000;if(name===needle)return 950;if(flat(name)===flat(needle))return 940;if(name.startsWith(needle))return 800-Math.min(100,name.length-needle.length);if(name.includes(needle))return 700-Math.min(100,name.length-needle.length);return -1}
module.exports=async function handler(req,res){const q=clean(req.query?.q||'');if(!q)return res.status(400).json({ok:false,error:'缺少股票名稱或代碼'});try{let hits=[];if(/^\d{4,6}$/.test(q)){const direct=await misByCode(q);if(direct)hits=[direct]}if(!hits.length){const [listed,otc]=await Promise.all([listedRows(),otcRows()]);hits=[...listed,...otc].map(x=>({...x,_score:rank(x,q)})).filter(x=>x._score>=0).sort((a,b)=>b._score-a._score||a.code.localeCompare(b.code))}if(!hits.length)return res.status(404).json({ok:false,error:'找不到對應的台股名稱或代碼'});const best=hits[0];res.setHeader('Cache-Control','s-maxage=3600, stale-while-revalidate=86400');return res.status(200).json({ok:true,code:best.code,name:best.name,market:best.market,symbol:`${best.code}${best.market==='上櫃'?'.TWO':'.TW'}`,matches:hits.slice(0,8).map(({_score,...x})=>x)})}catch(e){return res.status(500).json({ok:false,error:e?.message||'股票基本資料查詢失敗'})}}
